spring:
  application.name: api-gateway-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    registerWithEureka: false

server: 
  port: 8765
  
zuul:
  #prefix: /banks
  routes:
    bank:
      path: /0/*
      serviceId: bank
    bank1:
      path: /send1
      serviceId: bank1
      #url: http://localhost:8081
    bank2:
      path: /send2
      serviceId: bank2
    bank3:
      path: /send3
      serviceId: bank3